name: recipe_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.2.0
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.1

  # Firebase dependencies
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Local data storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  modal_progress_hud_nsn: ^0.5.1
  awesome_snackbar_content: ^0.1.3
  animated_splash_screen: ^1.3.0
  lottie: ^3.1.0
  web: ^1.1.1
  archive: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Screenshot 2024-02-15 192059.png
    - assets/no-internet.png
    - assets/app background.jpg
    - assets/first_one.png
    - assets/secound_one.png
    - assets/third_one.png
    - assets/icon.png
    - assets/animation.json
